# Generated by AI
SAMPLE_JOBS = [
    # scrape jobs — I/O-bound (url + delay)
    {"job_type": "scrape", "payload": {"url": "site-01.com", "delay": 0.5}},
    {"job_type": "scrape", "payload": {"url": "site-02.com", "delay": 1.2}},
    {"job_type": "scrape", "payload": {"url": "site-03.com", "delay": 0.3}},
    {"job_type": "scrape", "payload": {"url": "site-04.com", "delay": 0.8}},
    {"job_type": "scrape", "payload": {"url": "site-05.com", "delay": 1.5}},
    {"job_type": "scrape", "payload": {"url": "site-06.com", "delay": 0.4}},
    {"job_type": "scrape", "payload": {"url": "site-07.com", "delay": 0.9}},

    # process jobs — CPU-bound (n for factorial digit count)
    {"job_type": "process", "payload": {"n": 80000}},
    {"job_type": "process", "payload": {"n": 90000}},
    {"job_type": "process", "payload": {"n": 75000}},
    {"job_type": "process", "payload": {"n": 100000}},
    {"job_type": "process", "payload": {"n": 85000}},

    # deliberately failing jobs — to test error handling
    {"job_type": "scrape", "payload": {"url": "site-08.com"}},          # missing "delay" → KeyError
    {"job_type": "process", "payload": {}},                             # missing "n" → KeyError
    {"job_type": "nonexistent", "payload": {"foo": "bar"}},             # unregistered type → KeyError on lookup
]