# Generated by AI
SAMPLE_JOBS = [
    # scrape jobs — real URLs
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-1.html"}},
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-2.html"}},
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-3.html"}},
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-4.html"}},
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-5.html"}},

    # deliberate failures — test the error path with real HTTP
    {"job_type": "scrape", "payload": {"url": "http://books.toscrape.com/catalogue/page-9999.html"}},  # 404
    {"job_type": "scrape", "payload": {}},                          # missing "url" → KeyError
    {"job_type": "process", "payload": {}},                        # missing "n" → KeyError
    {"job_type": "nonexistent", "payload": {"foo": "bar"}},         # unregistered type
]